open! Alice_stdlib
open Alice_package
module Package_with_deps = Dependency_graph.Package_with_deps

type t =
  { package : Package.t
  ; transitive_dependency_closure_excluding_package : Package.Typed.lib_only_t list
  }

let of_package_with_deps package_with_deps =
  let package = Package_with_deps.package package_with_deps in
  let transitive_dependency_closure_excluding_package =
    Package_with_deps.transitive_dependency_closure_excluding_package package_with_deps
  in
  { package; transitive_dependency_closure_excluding_package }
;;

let source_code { package; _ } =
  let package_name = Package.name package in
  let package_name_s = Package_name.to_string package_name in
  let package_module_name = Module_name.of_package_name package_name in
  let internal_module_name = Module_name.internal_modules package_name in
  sprintf
    {|(* Public interface to package %S, generated by Alice. *)

(* This file's module is expected to be passed with -open when compiling each
   module of each package depending on this package. The public interface to
   this package is defined in a module named Lib, which is aliased to this
   package's name here, which will make the public interface to this module
   available to client code under a module named after this package. *)
module %s = %s.Lib

|}
    package_name_s
    (Module_name.to_string_uppercase_first_letter package_module_name)
    (Module_name.to_string_uppercase_first_letter internal_module_name)
;;
